version: "3.7"
services:
  db:
    image: postgres:15.3-alpine3.18
    container_name: db_app_tg
    command: -p 5535
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5535
    env_file:
      - .env
    environment:
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=C --lc-ctype=C

  telegram_bot_prozorro_v2:
    build:
      context: .
    env_file:
      - .env
    container_name: telegram_bot_prozorro_v2
    command: ["/telegram_bot_prozorro_v2/docker/run_bot.sh"]
    depends_on:
      - db
    environment:
      - TZ=Europe/Kiev

volumes:
  pgdata:
