"""initial

Revision ID: 4250c6ff2e48
Revises: 
Create Date: 2024-08-02 17:41:19.593656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4250c6ff2e48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_filter_tenders_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('DK021_2015', sa.String(), nullable=False),
    sa.Column('Status', sa.String(), nullable=False),
    sa.Column('Procurement_type', sa.String(), nullable=False),
    sa.Column('Region', sa.String(), nullable=False),
    sa.Column('Dispatch_time', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_filter_tenders_table')
    # ### end Alembic commands ###
